### ISSUE TITLE
`/usr/bin/eclipse -clean &` command failed

### ISSUE THREAD

**Issue by sathishkumarkk** [bepcyc/eclipse_installer#2]
While running the command `/usr/bin/eclipse -clean &`. I get the error as.

/opt/eclipse/eclipse: 1: /opt/eclipse/eclipse: Syntax error: ")" unexpected

**Comment by bepcyc** [comment]
Please provide an info on eclipse Linux version you've used.

**Comment by FisheyLP** [comment]
I get the same issue. I'm using eclipse Mars 2 for Linux

**Comment by bepcyc** [comment]
@sathishkumarkk and @FisheyLP, could you please confirm that the is fixed with @RobertCram commit? Just checkout latest master, thanks!
